/**
 * Public-reference facts observed from hero60rpg.com guide / patch notes.
 *
 * This is deliberately a compact behavioral contract, not copied product source
 * or content. Minute Vanguard remains an original product; these values exist
 * only to prevent accidental drift in the benchmark mechanics we intentionally
 * study.
 */
export const hero60Reference = {
  source: {
    guide: 'https://hero60rpg.com/guide',
    patchnotes: 'https://hero60rpg.com/patchnotes',
  },
  battle: {
    normalCooldownSec: 60,
    beginnerCooldownSec: 5,
    beginnerKillCount: 10,
    beginnerDefeatCooldownSec: 60,
    permanentCooldownSec: 50,
    rushCooldownSec: 10,
    maxTurns: 20,
    mutationChance: 0.01,
    mutationRewardMultiplier: 3,
    defeatGoldLossRatio: 0.5,
    defeatGoldRecoveryGemCost: 100,
    defeatHp: 1,
    drawExpRatio: 0.05,
    boostedDrawExpRatio: 0.10,
    rareGuaranteeGemCost: 10,
    rareGuaranteeWeights: [0.67, 0.24, 0.067, 0.02] as const,
    streakMultipliers: { two: 1.2, threeToFour: 1.5, fivePlus: 2 },
    jackpot: { x2: 0.08, x3: 0.03, x5: 0.01, x10: 0.003 },
    permanentStatChance: 0.01,
  },
  monsters: { levels: 13, perLevel: 50, total: 650, sequentialUnlock: true },
  cooldownPastime: { cells: 6, wrongTapPenalty: 3, grantsRewards: false, localBestOnly: true },
  battleLog: { localDisplayOptions: [10, 30, 50] as const, localDeviceSpecific: true },
  battleVisuals: { levelSpecificBackgrounds: true, documentedMonsterLevels: 12, dayparts: 4 },
  simpleBattle: { resultModal: false, fullOrbDropsDiscarded: true, defeatGoldRecoveryAvailable: false },
  mimicBank: { outcomeMultipliers: [0.1, 0.5, 1, 2] as const, withdrawGemCostMin: 10, withdrawGemCostMax: 30, exactOddsPublic: false },
  achievementTitles: { referenceCountAtLeast: 300, selectableDisplaySlots: 1 },
  arena: {
    dedicatedLoadout: { slots: ['weapon', 'armor', 'orb'] as const, free: true, appliesToAttackAndDefense: true, exactValuesPublic: false },
    pets: { everyTurn: true, tamerSecondPet: true, tamerSecondMultiplier: 0.6, tamerBonusPoints: 40, ninjaDodge: 0.30, wraithDodge: 0.70, exactBaseRatePublic: false },
    namedChallenge: { fromRanking: true, goldTransfer: false, sharesRatingRecordBarrierAndDailyWinLimit: true },
    achievementTitles: { tierReachCount: 10, championTitle: true },
    seasonRewards: {
      basedOnFinalTier: true,
      includesGold: true,
      gemMin: 3,
      gemMax: 120,
      masterGrantsCrest: true,
      unclaimedCarriesForward: true,
      claimSurface: 'menu-presents',
      tierTableInspectable: true,
      promotionResultShowsReward: true,
      championGetsBonus: true,
      championRecordedInHall: true,
      exactTierAmountsPublic: false,
    },
    weeklyResetWeekdayJst: 'monday',
    weeklyResetHourJst: 0,
    initialRating: 1000,
    minimumRating: 0,
    ratingUpsetGuardGap: 700,
    randomMatchUsesNearbyRating: true,
    firstMoveAttackerChance: 0.5,
    fixedCooldownSec: 60,
    sameOpponentWinsPerJstDay: 3,
    defenseBarrierSec: 2 * 60 * 60,
    attackerWinScoreDivisor: 100,
    attackerWinScoreMin: 2,
    attackerWinScoreMax: 40,
    attackerLossOrDrawScore: 1,
    defenderWinScoreDivisor: 3,
    defenseScoreFreeAllowance: 200,
    weekendDaysJst: ['friday', 'saturday', 'sunday'] as const,
    weekendScoreMultiplier: 2,
    championIsSeasonScoreRankOne: true,
    tierThresholds: [0, 300, 1000, 2500, 5000, 9000, 14000, 21000, 29000, 40000] as const,
    monsterCooldownUpgradesApply: false,
    rushApplies: false,
    gemSkipApplies: false,
    exactRatingFormulaPublic: false,
    exactSeasonResetFormulaPublic: false,
  },
  goldBags: {
    gemCosts: [30, 100, 300] as const,
    historyWins: 10,
    minimumWins: 2,
    ignoresGoldMultipliers: true,
  },
  timeBoosts: {
    durations: [
      { durationSec: 180, gemCost: 30 },
      { durationSec: 600, gemCost: 100 },
      { durationSec: 1800, gemCost: 300 },
    ] as const,
    rushCooldownSec: 10,
    expMultiplier: 2,
    goldMultiplier: 2,
    repurchaseWhileActive: false,
    cooldownSkipDuringRush: false,
  },
  progression: {
    stats: ['hp', 'attack', 'defense', 'magicAttack', 'magicDefense', 'luck'] as const,
    growthVarianceMin: 0.7,
    growthVarianceMax: 1.3,
    greatGrowthChance: 0.05,
    greatGrowthMultiplier: 2,
    jobChangeLevel: 30,
    jobs: 9,
    jobBonusRequirements: [30, 50, 100, 200] as const,
    jobBonusEscalationStartsAtTotalAward: 301,
    jobBonusEscalationStepLevels: 10,
    growthBonusByTotalAward: [
      { through: 200, percent: 5 },
      { through: 300, percent: 4 },
      { through: null, percent: 3 },
    ] as const,
    ninjaDodgeChance: 0.30,
    ninjaExecuteMaxChance: 0.15,
    wraithDodgeChance: 0.70,
    wraithMagicMaxMultiplier: 10,
    wraithHitDecayDivisor: 3,
    wraithHitMinimumMultiplier: 0.5,
    wraithUsesEquipment: false,
    tamerSecondPetMultiplier: 0.60,
    tamerPetDamageMultiplier: 1.40,
    tamerCaptureMultiplier: 1.50,
  },
  permanentUpgrades: {
    freeCooldownSkips: { gemCost: 500, dailyUses: 3 },
    cooldownReduction: { gemCost: 3000, fromSec: 60, toSec: 50 },
    expMultiplier: { gemCost: 2000, multiplier: 1.2 },
    goldMultiplier: { gemCost: 2000, multiplier: 1.2 },
    orbDropMultiplier: { gemCost: 2000, multiplier: 1.5 },
    drawExpMultiplier: { gemCost: 500, fromRatio: 0.05, toRatio: 0.10 },
  },
  orb: {
    ranks: ['F', 'E', 'D', 'C', 'B', 'A', 'S', 'SS', 'SSS'] as const,
    gachaSingleCost: 100,
    gachaTenCost: 1000,
    tenPullGuaranteesRankAOrHigher: true,
    tenPullGuaranteesSpecialEffect: true,
    baseCapacity: 10,
    fullInventoryReplacement: true,
    capacityExpansionGemCost: 100,
    rerollCostsByLockedStats: [50, 100, 200, 400] as const,
    maxRerollLockedStats: 3,
    combineMaterialCount: 4,
    combineCostsByTargetRank: {
      E: 30_000, D: 100_000, C: 300_000, B: 1_000_000,
      A: 3_000_000, S: 10_000_000, SS: 30_000_000, SSS: 100_000_000,
    } as const,
    matchingEffectUpgradeChancePerMaterial: 0.20,
    maxMatchingEffectUpgradeChance: 0.80,
    effectLadders: {
      gold: [3, 6, 9, 12, 15],
      exp: [3, 6, 9, 12, 15],
      greatGrowth: [3, 6, 9, 12, 15],
      critical: [5, 10, 15, 20, 25],
      evasion: [3, 6, 9, 12, 15],
      cooldown: [1, 2, 3, 4, 5],
    } as const,
    dropAndGachaCooldownMaxLevel: 3,
    equippedCanBeCombineParent: true,
    equippedCanBeCombineMaterial: false,
    protectedCanBeCombineParent: true,
    protectedCanBeCombineMaterial: false,
  },
  titles: {
    count: 52,
    slots: 5,
    copyThresholds: [1, 3, 6, 10, 15] as const,
    dropChance: 0.01,
    dailyShopOffers: 3,
    dailyShopGemCost: 300,
    paidResetGemCost: 300,
    costLimitAnchors: [
      { level: 1, cost: 4 },
      { level: 30, cost: 10 },
      { level: 120, cost: 16 },
      { level: 5000, cost: 40 },
    ] as const,
    maxedDropsAreWasted: true,
    clearsOnJobChange: true,
  },
  pet: { unlockKills: 30, captureChance: 0.01, maxPerMonster: 1, normalActiveSlots: 1, tamerActiveSlots: 2, growthBonusPctPerOwnedPet: 1, captureSupportGemCost: 2000, captureSupportMultiplierPerSlot: 2, captureSupportMaxMultiplier: 4, snackAutoIntervalSec: 3600, snackNaturalCap: 100, snackBundleGemCost: 100, snackBundleSize: 100, trainingLevelsPerGrowthBonusPct: 20, nicknameMaxChars: 12, emptyNicknameRestoresDefault: true, gachaLimitedCount: 50, gachaFirstSingleCost: 100, gachaSingleCost: 300, gachaTenCost: 3000, dailyPickupMultiplier: 2, tenPullGuarantee: false, duplicateSnacks: { common: 100, uncommon: 100, rare: 200, epic: 225, legendary: 250, boss: 300 } as const },
  daily: { missionCount: 5, categoryCount: 5, candidatePoolCount: 22, resetHourJst: 0, rewardByCompletedCount: [3, 3, 4, 5, 5] as const, totalGemReward: 20, loginCycleDays: 7 },
  loginBonus: { cycleDays: 7, day1Gold: 2_000, day7Gold: 20_000, day7Gems: 15, missedDayResetsCycle: true, intermediateRewardsPubliclySpecified: false },
  navigation: {
    bottomTabs: ['ショップ', '装備', 'バトル', 'コレクション', 'ランキング'] as const,
    equipmentTabs: ['武器', '防具', 'オーブ', 'ペット', '肩書き'] as const,
  },
} as const;
